name: CI

on: 
  push:
    branches:    
      - dev
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install yarn
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      run: |
        yarn test 
      env:
        CI: true
      
    - name: yarn build
      run: |
        yarn run build --if-present